SELECT UC.TABLE_NAME Child_table,
       UCC2.CONSTRAINT_NAME,
       UCC2.COLUMN_NAME,
       UCC.TABLE_NAME parent_table,
       UC.R_CONSTRAINT_NAME,
       UCC.COLUMN_NAME
   FROM (SELECT TABLE_NAME, CONSTRAINT_NAME, R_CONSTRAINT_NAME, CONSTRAINT_TYPE FROM dba_CONSTRAINTS where table_name='OAS_ICP') UC,
        (SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME FROM dba_CONS_COLUMNS) UCC,
        (SELECT TABLE_NAME, COLUMN_NAME, CONSTRAINT_NAME FROM dba_CONS_COLUMNS) UCC2
   WHERE UC.R_CONSTRAINT_NAME = UCC.CONSTRAINT_NAME
     AND UC.CONSTRAINT_NAME = UCC2.CONSTRAINT_NAME
     AND uc.constraint_type = 'R'
   ORDER BY 1,2,3,4
/
